image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build
  - name: Test
    command: dotnet test --filter "profile=parallel"

vscode:
  extensions:
    - muhammad-sammy.csharp
